### ISSUE TITLE
啊对对对，反洗脑，你怕是被洗脑了吧

### ISSUE THREAD

**Issue by qwerty6688** [hello-world-1989/what-to-see#1]
啊对对对，反洗脑，你怕是被洗脑了吧

你认为国外抹黑的还少吗？
就那BBC和大纪元看着就让人烦，一整条黑产链，整天不是BB就是C。

**Comment by qwerty6688** [comment]
别以为我无脑喷，我在这上高中，整天说的就是 共产主义 = 极权主义
连解释都不给你解释。

外面才是1984，洗脑都给你洗的明明白白，让你体验一下什么是 freedom is slavery


至于你那个团结起来，我不敢苟同。为什么中国会要墙？如果中国没有墙就会思想渗透（苏联毒课本），那问题来了，为什么美国不要墙？
因为美国已经从头到尾把反共的环境建设起来了。
没法访问谷歌，我学校也没法访问百度，连中国政府网站都屏蔽了，用的还是老招数：DNS污染 + Chrome扩展，真正实现了 Big brother is wathching you。



--------------------------分割线------------------------



墙的制度的确有问题，但是这样做是有原因的，不要被那些SB利用了。况且现在翻墙已经没人管你了，只要你不发奇怪的言论就行。最后一点，大纪元和BBC也和拆墙没啥关系啊，哪个会翻墙的还启蒙运动？不都是翻墙找资料的吗？（或者有一些不可告人的外快？）

**Comment by hello-world-1989** [comment]
翻墙已经没人管你
-------------------
现在翻墙要入刑

多看看境外新闻，出社会亲身体验下， 出了事情警察会不会管你

**Comment by qwerty6688** [comment]
> ## 翻墙已经没人管你
> 现在翻墙要入刑
> 
> 多看看境外新闻，出社会亲身体验下， 出了事情警察会不会管你

我在这U S呢，哥
况且你看下我下一句说的什么（只要你不发奇怪的言论就行。），至少之前翻了好几年鸟都没鸟我。
